// src/lib/recent-work.ts
//
// Auto-generated by the Linfordy platform's proofpop-capture handler.
// New entries are appended by /api/webhooks/proofpop-capture when a
// job_capture_complete event lands. Do not hand-edit unless you also
// remove the corresponding MDX file under src/content/recent-work/.

export interface RecentWorkEntry {
  slug: string;
  title: string;
  service_category: string;
  neighborhood: string;
  city: string;
  state: string;
  completed_at: string;
  tech_name: string;
  photo_urls: string[];
  voice_summary: string;
}

export const recentWork: RecentWorkEntry[] = [
  {
    slug: "emergency-pipe-repair-sandy-20260614-g7h8i9",
    title: "Emergency Pipe Repair",
    service_category: "emergency",
    neighborhood: "",
    city: "Sandy",
    state: "UT",
    completed_at: "2026-06-14T15:22:00.000Z",
    tech_name: "Mike",
    photo_urls: [
      "https://abdeuofvwjouxxtxrhan.supabase.co/storage/v1/object/public/crm-photos/e6a2f3e8-8655-48b2-923d-861e277ac57a/test-card-emergency-1781372509/98a069ad5e430189.jpg",
      "https://abdeuofvwjouxxtxrhan.supabase.co/storage/v1/object/public/crm-photos/e6a2f3e8-8655-48b2-923d-861e277ac57a/test-card-emergency-1781372509/87b48af1b6770986.jpg",
    ],
    voice_summary: "Wasatch Plumbing responded to an emergency call in Sandy after a homeowner discovered water pooling under their kitchen sink. The supply line had developed a pinhole leak. The technician isolated the water supply, replaced the faulty copper section, and pressure tested the repair. Water restored within 45 minutes of arrival.",
  },
  {
    slug: "drain-cleaning-riverton-20260612-d4e5f6",
    title: "Drain Cleaning",
    service_category: "drain_cleaning",
    neighborhood: "",
    city: "Riverton",
    state: "UT",
    completed_at: "2026-06-12T11:45:00.000Z",
    tech_name: "Chris",
    photo_urls: [
      "https://abdeuofvwjouxxtxrhan.supabase.co/storage/v1/object/public/crm-photos/e6a2f3e8-8655-48b2-923d-861e277ac57a/test-card-drain-1781372509/55eed885faa91bc3.jpg",
      "https://abdeuofvwjouxxtxrhan.supabase.co/storage/v1/object/public/crm-photos/e6a2f3e8-8655-48b2-923d-861e277ac57a/test-card-drain-1781372509/e511fc251c593a9d.jpg",
    ],
    voice_summary: "A main kitchen drain was completely cleared at a Riverton residence after progressive slow drain issues. The technician ran a cable 35 feet through the line and used a hydro-jet to scour grease buildup from the pipe walls. Before-and-after camera footage confirmed a fully clear line.",
  },
  {
    slug: "water-heater-south-jordan-20260610-a1b2c3",
    title: "Water Heater Replacement",
    service_category: "water_heater",
    neighborhood: "Daybreak",
    city: "South Jordan",
    state: "UT",
    completed_at: "2026-06-10T09:30:00.000Z",
    tech_name: "Dave",
    photo_urls: [
      "https://abdeuofvwjouxxtxrhan.supabase.co/storage/v1/object/public/crm-photos/e6a2f3e8-8655-48b2-923d-861e277ac57a/test-card-heater-1781372509/883259077548d80d.jpg",
      "https://abdeuofvwjouxxtxrhan.supabase.co/storage/v1/object/public/crm-photos/e6a2f3e8-8655-48b2-923d-861e277ac57a/test-card-heater-1781372509/4ddc369ccd4c6a71.jpg",
    ],
    voice_summary: "A 50-gallon gas water heater was replaced at a Daybreak-area residence in South Jordan after the 12-year-old unit developed a leak at the bottom of the tank. The technician installed a new Rheem Performance Plus unit, upgraded supply lines to braided stainless steel, and brought the gas connection to current code.",
  },
];
